In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
data= pd.read_csv("C:/Users/Rakes/Downloads/diabetes.csv")

In [12]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [14]:
data.tail(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
758,1,106,76,0,0,37.5,0.197,26,0
759,6,190,92,0,0,35.5,0.278,66,1
760,2,88,58,26,16,28.4,0.766,22,0
761,9,170,74,31,0,44.0,0.403,43,1
762,9,89,62,0,0,22.5,0.142,33,0
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [24]:
x=data[0:10]

In [26]:
x

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [18]:
data.cumsum()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,7,233,138,64,0,60.2,0.978,81,1
2,15,416,202,64,0,83.5,1.650,113,2
3,16,505,268,87,94,111.6,1.817,134,2
4,16,642,308,122,262,154.7,4.105,167,3
...,...,...,...,...,...,...,...,...,...
763,2944,92385,52801,15691,61174,24446.8,361.152,25402,267
764,2946,92507,52871,15718,61174,24483.6,361.492,25429,267
765,2951,92628,52943,15741,61286,24509.8,361.737,25459,267
766,2952,92754,53003,15741,61286,24539.9,362.086,25506,268
767,2953,92847,53073,15772,61286,24570.3,362.401,25529,268

In [30]:
x.cumsum()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,7,233,138,64,0,60.2,0.978,81,1
2,15,416,202,64,0,83.5,1.650,113,2
3,16,505,268,87,94,111.6,1.817,134,2
4,16,642,308,122,262,154.7,4.105,167,3
5,21,758,382,122,262,180.3,4.306,197,3
6,24,836,432,154,350,211.3,4.554,223,4
7,34,951,432,154,350,246.6,4.688,252,4
8,36,1148,502,199,893,277.1,4.846,305,5
9,44,1273,598,199,893,277.1,5.078,359,6

In [47]:
data.dtype

AttributeError: 'DataFrame' object has no attribute 'dtype'

In [49]:
data.count()

Pregnancies                 768
Glucose                     768
BloodPressure               768
SkinThickness               768
Insulin                     768
BMI                         768
DiabetesPedigreeFunction    768
Age                         768
Outcome                     768
dtype: int64

In [51]:
data.index

RangeIndex(start=0, stop=768, step=1)

In [55]:
data[:768:5]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
5,5,116,74,0,0,25.6,0.201,30,0
10,4,110,92,0,0,37.6,0.191,30,0
15,7,100,0,0,0,30.0,0.484,32,1
20,3,126,88,41,235,39.3,0.704,27,0
...,...,...,...,...,...,...,...,...,...
745,12,100,84,33,105,30.0,0.488,46,0
750,4,136,70,0,0,31.2,1.182,22,1
755,1,128,88,39,110,36.5,1.057,37,1
760,2,88,58,26,16,28.4,0.766,22,0
765,5,121,72,23,112,26.2,0.245,30,0

In [57]:
data[0:76:10]

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
10,4,110,92,0,0,37.6,0.191,30,0
20,3,126,88,41,235,39.3,0.704,27,0
30,5,109,75,26,0,36.0,0.546,60,0
40,3,180,64,25,70,34.0,0.271,26,0
50,1,103,80,11,82,19.4,0.491,22,0
60,2,84,0,0,0,0.0,0.304,21,0
70,2,100,66,20,90,32.9,0.867,28,1

In [59]:
data.size

6912

In [73]:
ts_stand = ((data - data.mean()) / data.std())
ts_stand

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.639530,0.847771,0.149543,0.906679,-0.692439,0.203880,0.468187,1.425067,1.365006
1,-0.844335,-1.122665,-0.160441,0.530556,-0.692439,-0.683976,-0.364823,-0.190548,-0.731643
2,1.233077,1.942458,-0.263769,-1.287373,-0.692439,-1.102537,0.604004,-0.105515,1.365006
3,-0.844335,-0.997558,-0.160441,0.154433,0.123221,-0.493721,-0.920163,-1.040871,-0.731643
4,-1.141108,0.503727,-1.503707,0.906679,0.765337,1.408828,5.481337,-0.020483,1.365006
...,...,...,...,...,...,...,...,...,...
763,1.826623,-0.622237,0.356200,1.721613,0.869464,0.115094,-0.908090,2.530487,-0.731643
764,-0.547562,0.034575,0.046215,0.405181,-0.692439,0.609757,-0.398023,-0.530677,-0.731643
765,0.342757,0.003299,0.149543,0.154433,0.279412,-0.734711,-0.684747,-0.275580,-0.731643
766,-0.844335,0.159683,-0.470426,-1.287373,-0.692439,-0.240048,-0.370859,1.169970,1.365006
767,-0.844335,-0.872451,0.046215,0.655930,-0.692439,-0.201997,-0.473476,-0.870806,-0.731643

NameError: name 'ts_stand' is not defined